### ISSUE TITLE
Assert Test Results

### ISSUE THREAD

**Issue by barrotsteindev** [ferreiradaselva/mathc#6] opened 2017-10-09 19:01 UTC
tests should assert the returned value is equal to the expected value, and fail if otherwise.
the test can be run as is or using a unit testing framework, which ever option is found to be the best fit.
Any input?

**Comment by felselva** [comment] 2017-10-09 19:13
The problem is that `float` precision can't guarantee that comparison like `i == j` is true, even if both variables are `0.0f`. Thus printing the values instead of comparing.

I currently have a function `int nearly_equal(float a, float b, float epsilon)` to make approximate comparisons, but I still didn't check what would be an appropriate `epsilon` value.

**Comment by barrotsteindev** [comment] 2017-10-09 19:19
OK, I will also have a look at this tomorrow and once we figure this out we can have automatic testing for every push, streamlining the development effort.

**Comment by RandyGaul** [comment] 2017-10-09 19:24
Unit tests for floating point stuff are pretty difficult to write. A good epsilon needs to be chosen or computed for each different test, and should scale itself relative to the largest magnitude of a float during computation.

For example, when dotting vectors together (especially when they aren't normalize) some large numbers can appear briefly before being sqrt'd, or perhaps used in a division. These large results can skew the necessity of an epsilon's size dramatically, and be tricky to find + diagnose.

Typically floating point related unit tests should be A) written by someone who has good knowledge + some experience with choosing/computing epsilons, B) make use of fuzzy comparisons or perhaps sign tests where appropriate.

That's why for example Google Test doesn't even support floating point comparisons in the majority of it's unit test macros.

**Comment by barrotsteindev** [comment] 2017-10-09 19:30
That is true, but we can at least figure a way that the tests can at least tell you if you changed the result in a major way.
for this google test has an almost equal macro for [floats](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#floating-point-comparison).

**Comment by felselva** [comment] 2017-10-09 22:09
I was able to get pretty good results with the macro `FLT_EPSILON` from `<float.h>`. Sometimes the value of `FLT_EPSILON` is too small for the test and will result in a difference that should be ignored, then the test is run again with `FLT_EPSILON * 10.0f`. So, the tests have results like this:

```
Normalize vector...
	Expected  0.8573,  0.5149
	  Actual  0.8573,  0.5149        ~passed with greater error margin~

Slide vector by normal...
	Expected  1.0000,  0.0000
	  Actual  1.0000,  0.0000        ~passed~
```
Tests with `~passed~` and `~passed with greater error margin~` are considered success, otherwise it gives `~failed~`. It is arbitrary, but think it's good enough, so I will close the issue.

**Closed as completed by felselva** 2017-10-09 22:09 UTC
